spring.application.name=backend

# MongoDB Configuration
spring.mongodb.uri=mongodb://localhost:27017/weekly_report_db

# JWT Configuration
# Use a strong, 32+ character secret key
jwt.secret=SisencoDigitalTechnicalAssignmentSecretKey2026
jwt.expiration=86400000
jwt.refreshExpiration=604800000

# Default Manager Credentials
admin.default.fullname=System Admin
admin.default.email=admin@sisenco.com
admin.default.password=admin123